import React, { useState } from "react";

const Faqs = () => {
  const faqsData = [
    {
      question: "What is an AI girlfriend?",
      answer:
        "An AI girlfriend means an AI character generated by artificial intelligence tech. It can be an image, a video, or a virtual character that can interact with you. AINude.AI is one of the best AI nude girl image generators and undress AI you can use to customize the girl in your dream.",
    },
    {
      question: "Is it possible to have an AI nude girlfriend?",
      answer:
        "Yes, you can have your AI nude girlfriend or waifu. In order to have a DIY AI girlfriend image, you need to choose an online AI nude generator that applies undress AI technology. AINude.AI is one of the best AI girlfriend generators where you can undress a real photo with one click.",
    },
    {
      question: "How is my personal information handled on AINude.AI?",
      answer:
        "AINude.AI handles your data with the utmost care and adheres to strict data protection practices. Any personal information you provide while using AINude.AI's undress AI service is treated as confidential and stored securely. We do not sell or share your information with any third parties without your explicit consent.",
    },
    {
      question: "What is an AI girlfriend?",
      answer:
        "An AI girlfriend means an AI character generated by artificial intelligence tech. It can be an image, a video, or a virtual character that can interact with you. AINude.AI is one of the best AI nude girl image generators and undress AI you can use to customize the girl in your dream.",
    }
  ];

  const [visibleIndex, setVisibleIndex] = useState(null);

  const toggleAnswer = (index) => {
    setVisibleIndex(visibleIndex === index ? null : index);
  };

  return (
    <div className="desktop px-4 pt-6 pb-8 xl:px-10 xl:pt-[84px] xl:pb-[168px]">
      <h2 className="mb-4 text-center text-[28px] font-bold text-black/95 xl:mb-12 xl:text-5xl">
        AINude.AI Deepnude Generator FAQs
      </h2>
      <ul>
        {faqsData.map((faq, index) => (
          <li
            key={index}
            className="mb-3 cursor-pointer rounded-base bg-footer p-4 first:mt-0 xl:mt-5 xl:p-5"
            onClick={() => toggleAnswer(index)}
          >
            <h3 className="mb-2 flex items-center justify-between text-base xl:text-xl font-bold text-black/95">
              <span className="pr-4">
                {index + 1}. {faq.question}
              </span>
              <svg width={16} height={16} xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M8 2a1 1 0 0 1 1 1v4h4a1 1 0 0 1 0 2H9v4a1 1 0 0 1-2 0V9H3a1 1 0 1 1 0-2h4V3a1 1 0 0 1 1-1z"
                  fill="currentColor"
                  fillRule="evenodd"
                  opacity="0.8"
                />
              </svg>
            </h3>
            <p className={`text-sm xl:text-base leading-6 text-black ${visibleIndex === index ? '' : 'hidden'}`}>
              {faq.answer}
            </p>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Faqs;
